name: 'Ref Comment in Commit'

# Make it possible to reference a GH comment in a commit message.
#
# This file has been created from
# https://github.com/verkstedt/.github/blob/main/workflow-templates/ref-comment-in-commit.yaml
#
# IF YOU MODIFY IT IN ANY WAY, DESCRIBE IT IN THE COMMENT HERE
# to make updating in the future easier.

on:
  push:

jobs:
  ref-comments:
    name: 'Ref Comment in Commit'
    runs-on: ubuntu-latest
    steps:
      - name: 'Ref Comment in Commit'
        uses: 'verkstedt/actions/ref-comment-in-commit@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
